workflows:
  ios-testflight:
    name: iOS TestFlight
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      # 代码签名配置
      ios_signing:
        distribution_type: app_store
        bundle_identifier: "com.elixir.esports"
      vars:
        APP_ID: "com.elixir.esports"
        APPLE_ID: "6747395204"
        KEY_ID: "4PJ2JDKKG9"
        ISSUER_ID: "e7251b06-66a7-4e3e-a955-fc319af14a54"
        # 私钥通过环境变量注入（已勾选Secret，不会暴露）
        APP_STORE_CONNECT_PRIVATE_KEY: $APP_STORE_CONNECT_PRIVATE_KEY
    scripts:
      - name: 初始化密钥链并获取签名文件
        script: |
          keychain initialize
          # 使用环境变量中的密钥获取签名文件
          app-store-connect fetch-signing-files "$APP_ID" \
            --type IOS_APP_STORE \
            --create \
            --issuer-id "$ISSUER_ID" \
            --key-id "$KEY_ID" \
            --private-key "$APP_STORE_CONNECT_PRIVATE_KEY"
          keychain add-certificates
          xcode-project use-profiles
      - name: 安装Flutter依赖
        script: |
          flutter pub get
          cd ios && pod install && cd ..
      - name: 自动递增Build Number
        script: |
          LATEST_BUILD=$(app-store-connect get-latest-testflight-build-number \
            --platform=IOS \
            "$APPLE_ID" \
            --issuer-id "$ISSUER_ID" \
            --key-id "$KEY_ID" \
            --private-key "$APP_STORE_CONNECT_PRIVATE_KEY")
          if [ -z "$LATEST_BUILD" ]; then
            LATEST_BUILD=0
          fi
          NEW_BUILD=$((LATEST_BUILD + 1))
          echo "新Build Number: $NEW_BUILD"
      - name: 构建IPA
        script: |
          flutter build ipa --release \
            --build-number="$NEW_BUILD" \
            --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    publishing:
      app_store_connect:
        # 手动指定API密钥（替代团队集成）
        auth: api_key
        api_key:
          key_id: $KEY_ID
          issuer_id: $ISSUER_ID
          private_key: $APP_STORE_CONNECT_PRIVATE_KEY
        # 核心：提交到TestFlight
        submit_to_testflight: true
        expire_build_submitted_for_review: true
        beta_groups:
          - "Internal Testers"
        wait_for_processing: true